# Generated by Django 2.1.5 on 2019-01-21 09:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(default=3)),
                ('title', models.CharField(max_length=64)),
                ('summary', models.TextField()),
                ('ip', models.GenericIPAddressField()),
                ('submission_date', models.DateTimeField(default=datetime.datetime.now)),
                ('company', models.CharField(max_length=255)),
                ('reviewer', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
